title: Christopher Rossi
tagline: My Portfolio
description: My Portfolio
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  another_url: another value
